import { OpenAIService } from './openai/openai.service';
import { Body, Controller, HttpStatus, Post } from '@nestjs/common';
import { ApiOperation, ApiResponse, ApiTags, ApiBody } from '@nestjs/swagger';
import { AnswerResponseDto } from './answer.dto';
import { AskQuestionDto } from './question.dto';

@ApiTags('lucia')
@Controller('api/v1/lucia')
export class AppController {
  constructor(private readonly OpenAIService: OpenAIService) {}

  @Post('/ask')
  @ApiOperation({
    summary: 'Get an answer from Lucía',
    description:
      'This endpoint takes a question from the user and returns an answer generated by Lucía using the OpenAI service.',
  })
  @ApiBody({
    description: 'The question to ask Lucía',
    type: AskQuestionDto,
  })
  @ApiResponse({
    status: HttpStatus.OK,
    description: 'The answer was successfully generated.',
    type: AnswerResponseDto,
  })
  @ApiResponse({
    status: HttpStatus.BAD_REQUEST,
    description: 'Invalid input data.',
  })
  async getAnswer(@Body() body: AskQuestionDto): Promise<AnswerResponseDto> {
    const answer = await this.OpenAIService.getAnswer(body.question);
    return new AnswerResponseDto(HttpStatus.OK, 'Success', answer);
  }
}
